CC = gcc     # Flag for implicit rules
CFLAGS = -g  # Flag for implicit rules. Turn on debug info

# Implicit rule #1: main is built via the C linker implicit rule
# Implicit rule #2: main.o is built via the C compilation implicit rule,
	# because main.c exists
main: main.c

main.c:
	echo "int main() { return 0; }" > main.c

clean:
	rm -f main*
